"""Task 4: Markdown-heading chunking, embedding, and ChromaDB indexing."""

import hashlib
import argparse
import json
import os
import re
from pathlib import Path
from typing import Any
import time

PROJECT_DIR = Path(__file__).resolve().parent.parent
STANDARDIZED_DIR = PROJECT_DIR / "data" / "standardized"
CHROMA_DIR = PROJECT_DIR / "chroma_db"

# Heading-aware chunks preserve policy/article structure. A second recursive pass
# limits very long sections; 500 characters is compact enough for focused retrieval,
# while 50 characters of overlap retain context at artificial split boundaries.
CHUNK_SIZE = 500
CHUNK_OVERLAP = 50
CHUNKING_METHOD = "markdown_header"

# BGE-M3 is multilingual and works well for Vietnamese and English documents.
EMBEDDING_MODEL = "BAAI/bge-m3"
EMBEDDING_DIM = 1024
VECTOR_STORE = "chromadb"
COLLECTION_NAME = "ecommerce_support_docs"
CHUNKS_PREVIEW_FILE = PROJECT_DIR / "data" / "chunks_preview.txt"

HEADERS_TO_SPLIT_ON = [
    ("#", "title"),
    ("##", "section"),
    ("###", "subsection"),
]


def _parse_front_matter(text: str) -> tuple[dict, str]:
    """Parse the simple JSON-valued YAML front matter generated by Task 3."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}, text

    metadata: dict[str, Any] = {}
    for line in text[4:end].splitlines():
        if ":" not in line:
            continue
        key, raw_value = line.split(":", 1)
        try:
            metadata[key.strip()] = json.loads(raw_value.strip())
        except json.JSONDecodeError:
            metadata[key.strip()] = raw_value.strip().strip("'\"")
    return metadata, text[end + 5 :].lstrip()


def _scalar_metadata(metadata: dict) -> dict:
    """Convert metadata to scalar values accepted by ChromaDB."""
    result = {}
    for key, value in metadata.items():
        if value is None:
            continue
        if isinstance(value, (str, int, float, bool)):
            result[key] = value
        else:
            result[key] = json.dumps(value, ensure_ascii=False)
    return result


def load_documents() -> list[dict]:
    """Load standardized Markdown and its front matter metadata."""
    if not STANDARDIZED_DIR.exists():
        return []

    documents = []
    for md_file in sorted(STANDARDIZED_DIR.rglob("*.md")):
        if md_file.name.startswith("."):
            continue
        raw_text = md_file.read_text(encoding="utf-8")
        front_matter, content = _parse_front_matter(raw_text)
        if not content.strip():
            continue

        relative = md_file.relative_to(STANDARDIZED_DIR)
        doc_type = relative.parts[0] if len(relative.parts) > 1 else "unknown"
        metadata = {
            "source": md_file.name,
            "source_path": relative.as_posix(),
            "type": doc_type,
            **front_matter,
        }
        documents.append({"content": content.strip(), "metadata": metadata})
    return documents


def _split_by_headings(markdown: str) -> list[tuple[str, dict]]:
    """Split Markdown by H1-H3 while carrying the heading hierarchy forward."""
    sections: list[tuple[str, dict]] = []
    hierarchy: dict[str, str] = {}
    buffer: list[str] = []
    heading_pattern = re.compile(r"^(#{1,3})\s+(.+?)\s*$")
    keys = {1: "title", 2: "section", 3: "subsection"}

    def flush() -> None:
        content = "\n".join(buffer).strip()
        if content:
            sections.append((content, hierarchy.copy()))

    for line in markdown.splitlines():
        match = heading_pattern.match(line)
        if match:
            flush()
            buffer.clear()
            level = len(match.group(1))
            hierarchy[keys[level]] = match.group(2).strip()
            for deeper_level in range(level + 1, 4):
                hierarchy.pop(keys[deeper_level], None)
            # Keep the heading in the chunk so embeddings see its meaning.
            buffer.append(line)
        else:
            buffer.append(line)
    flush()
    return sections


def _split_long_section(text: str) -> list[str]:
    """Recursively limit a section to CHUNK_SIZE with CHUNK_OVERLAP."""
    if len(text) <= CHUNK_SIZE:
        return [text]
    try:
        from langchain_text_splitters import RecursiveCharacterTextSplitter

        splitter = RecursiveCharacterTextSplitter(
            chunk_size=CHUNK_SIZE,
            chunk_overlap=CHUNK_OVERLAP,
            separators=["\n\n", "\n", ". ", "; ", ", ", " ", ""],
            length_function=len,
        )
        return [part.strip() for part in splitter.split_text(text) if part.strip()]
    except ImportError:
        # Dependency-free fallback used by the tests and minimal environments.
        parts = []
        start = 0
        while start < len(text):
            end = min(start + CHUNK_SIZE, len(text))
            if end < len(text):
                boundary = max(text.rfind("\n", start, end), text.rfind(" ", start, end))
                if boundary > start + CHUNK_SIZE // 2:
                    end = boundary
            parts.append(text[start:end].strip())
            if end >= len(text):
                break
            start = max(end - CHUNK_OVERLAP, start + 1)
        return [part for part in parts if part]


def chunk_documents(documents: list[dict]) -> list[dict]:
    """Chunk documents by Markdown headings, then limit oversized sections."""
    chunks = []
    for document in documents:
        document_chunks = 0
        for section_text, heading_metadata in _split_by_headings(document["content"]):
            for part in _split_long_section(section_text):
                chunks.append({
                    "content": part,
                    "metadata": {
                        **document.get("metadata", {}),
                        **heading_metadata,
                        "chunk_index": document_chunks,
                    },
                })
                document_chunks += 1
    return chunks


def export_chunks_txt(
    chunks: list[dict], output_path: Path = CHUNKS_PREVIEW_FILE
) -> Path:
    """Export every chunk and its heading metadata to a human-readable TXT file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "TASK 4 - MARKDOWN HEADING CHUNKS",
        f"Total chunks: {len(chunks)}",
        f"Chunk size: {CHUNK_SIZE}",
        f"Chunk overlap: {CHUNK_OVERLAP}",
        "=" * 100,
    ]

    for position, chunk in enumerate(chunks, 1):
        metadata = chunk.get("metadata", {})
        content = chunk.get("content", "")
        lines.extend([
            "",
            f"CHUNK {position}/{len(chunks)}",
            "-" * 100,
            f"Length       : {len(content)} characters",
            f"Source       : {metadata.get('source', 'N/A')}",
            f"Document ID  : {metadata.get('document_id', 'N/A')}",
            f"Document type: {metadata.get('document_type', metadata.get('type', 'N/A'))}",
            f"Category     : {metadata.get('category', 'N/A')}",
            f"Title        : {metadata.get('title', 'N/A')}",
            f"Section      : {metadata.get('section', 'N/A')}",
            f"Subsection   : {metadata.get('subsection', 'N/A')}",
            f"Chunk index  : {metadata.get('chunk_index', 'N/A')}",
            "",
            "CONTENT:",
            content,
            "=" * 100,
        ])

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path





def embed_chunks(chunks: list[dict]) -> list[dict]:
    """Embed chunks locally bằng GPU và hiển thị thời gian xử lý."""
    if not chunks:
        return chunks

    try:
        import torch
        from sentence_transformers import SentenceTransformer
        from tqdm.auto import tqdm
    except ImportError as exc:
        raise RuntimeError(
            "Thiếu thư viện embedding. Chạy: pip install torch sentence-transformers tqdm"
        ) from exc

    # if not torch.cuda.is_available():
    #     raise RuntimeError(
    #         "CUDA không khả dụng. Hãy kiểm tra NVIDIA driver và PyTorch CUDA."
    #     )

    # device = "cuda"
    # print(f"Embedding device: {device}")
    # print(f"GPU: {torch.cuda.get_device_name(0)}")

    start_time = time.perf_counter()

    model = SentenceTransformer(
        EMBEDDING_MODEL,
        # device=device,
    )

    texts = [chunk["content"] for chunk in chunks]

    embeddings = model.encode(
        texts,
        batch_size=16,
        show_progress_bar=True,  # SentenceTransformer sử dụng tqdm
        normalize_embeddings=True,
        convert_to_numpy=True,
    )

    for chunk, embedding in tqdm(
        zip(chunks, embeddings),
        total=len(chunks),
        desc="Saving embeddings",
        unit="chunk",
    ):
        chunk["embedding"] = embedding.tolist()

    elapsed_time = time.perf_counter() - start_time
    throughput = len(chunks) / elapsed_time if elapsed_time > 0 else 0

    print(f"Đã xử lý: {len(chunks)} chunks")
    print(f"Tổng thời gian: {elapsed_time:.2f} giây")
    print(f"Tốc độ: {throughput:.2f} chunks/giây")

    return chunks


def index_to_vectorstore(chunks: list[dict]) -> int:
    """Upsert embedded chunks into a persistent cosine Chroma collection."""
    if not chunks:
        return 0
    if any("embedding" not in chunk for chunk in chunks):
        raise ValueError("All chunks must contain an embedding before indexing")
    try:
        import chromadb
    except ImportError as exc:
        raise RuntimeError("ChromaDB is missing. Run: pip install chromadb") from exc

    CHROMA_DIR.mkdir(parents=True, exist_ok=True)
    client = chromadb.PersistentClient(path=str(CHROMA_DIR))
    collection = client.get_or_create_collection(
        name=COLLECTION_NAME,
        metadata={"hnsw:space": "cosine", "embedding_model": EMBEDDING_MODEL},
    )

    for start in range(0, len(chunks), 100):
        batch = chunks[start : start + 100]
        ids = []
        for chunk in batch:
            metadata = chunk["metadata"]
            identity = f"{metadata.get('document_id', metadata.get('source'))}:{metadata['chunk_index']}"
            ids.append(hashlib.sha256(identity.encode("utf-8")).hexdigest()[:32])
        collection.upsert(
            ids=ids,
            documents=[chunk["content"] for chunk in batch],
            embeddings=[chunk["embedding"] for chunk in batch],
            metadatas=[_scalar_metadata(chunk["metadata"]) for chunk in batch],
        )
    return len(chunks)


def run_pipeline() -> None:
    """Run load -> heading chunk -> embed -> persistent index."""
    print("=" * 60)
    print("Task 4: Markdown Heading Chunking & ChromaDB Indexing")
    print(f"Chunking: {CHUNKING_METHOD}, size={CHUNK_SIZE}, overlap={CHUNK_OVERLAP}")
    print(f"Embedding: {EMBEDDING_MODEL} ({EMBEDDING_DIM} dimensions)")
    print("=" * 60)

    documents = load_documents()
    print(f"Loaded {len(documents)} documents")
    chunks = chunk_documents(documents)
    print(f"Created {len(chunks)} heading-aware chunks")
    chunks = embed_chunks(chunks)
    indexed = index_to_vectorstore(chunks)
    print(f"Indexed {indexed} chunks at: {CHROMA_DIR}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Task 4 chunking and indexing")
    parser.add_argument(
        "--preview",
        action="store_true",
        help="Export chunks to data/chunks_preview.txt without embedding/indexing",
    )
    args = parser.parse_args()
    if args.preview:
        preview_chunks = chunk_documents(load_documents())
        preview_path = export_chunks_txt(preview_chunks)
        print(f"Exported {len(preview_chunks)} chunks to: {preview_path}")
    else:
        run_pipeline()
